### PR TITLE
Update License.txt

### PR DESCRIPTION
**Pull request by chiefken**
Great project. Cant wait for it to launch and invest heavily in it.

### CODE REVIEW

**Comment by Pearlruby11** [comment]
Send it

**Comment by chiefken** [comment]
Update License.txt by chiefken · Pull Request #22 · ChoiceCoin/Voting

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Update License.txt by chiefken · Pull Request #22 · ChoiceCoin/Voting

Great project. Cant wait for it to launch and invest heavily in it.
 |

 |

 |





XAK732T5HNXWVU5F6YPPJDQJIKHXUJATPIM42XIDBKVRBM2L4ZTJAEP35I

    On Saturday, September 11, 2021, 10:11:21 PM GMT+1, Pearlruby11 ***@***.***> wrote:  
 
 


Send it

**Review by BigScheun — COMMENTED** [review]
Nice project, let's pump it

**Comment by chiefken** [comment]
great project. 100% into this

**Comment by chiefken** [comment]
i love it

**Pull request closed without merging**
