### PR TITLE
Licenses

### PR DESCRIPTION
**Pull request by Teesticks**

### CODE REVIEW

**Comment by solarlee08** [comment]
This is great project keep it up guys algo will surprise the world

**Comment by Dhianamic** [comment]
AKXY6IJYDSCVQU6B53PNDZGCAKK62ZACWWUB5XJ5FGSCLDHB5DYJLHMAZU

**Comment by kekejstme** [comment]
Choice coin is a project to hold onto. Fairness and transparency.

**Comment by Dhianamic** [comment]
The team has been an inspiration in their innovative approaches towards achieving the project goals and visions

**Pull request closed without merging**
