### PR TITLE
fionnachan / Refinement Bash

### PR DESCRIPTION
**Pull request by fionnachan**
[View deployed site here](https://choice-refinement.netlify.app/)

#### Refactoring
- [x] remove package-lock.json because there is already yarn.lock and they should not exist together
- [x] remove jquery and use `useRef` to control style changes for expansion / collapse of tabs in FAQ and Voting cards
- [x] add styled-components for styling
- [x] add typescript to help development & better code maintenance
    - move some .js to .tsx
    - use type and interface
- [x] move ElecitonCard out of Election List as a separate component
- [x] move FAQ question item out of FAQ as a separate component
- [x] remove unused files
- [x] use AlgoExplorer API for testnet instead of purestake with hardcoded token in the code base

#### Features
- [x] connect wallet button on header
- [x] add Algorand wallet option
- [x] show user's Choice coin balance
- [x] show user's committed Choice coin
- [x] allow user to input Choice coin amount for voting
- [x] add icons to dark/light mode toggle

### Screenshot
Connect Wallet button
image
Algorand Wallet option
image
Input for Choice coin vote amount & header commitment amount
image

For #984

### CODE REVIEW

**Comment by Bhaney44** [comment]
This is seriously amazing!

**Comment by Arch222** [comment]
Also, the 'show results' tab does not show anything.

**Comment by ChoiceCoin** [comment]
I added the original [AlphaVote1](https://github.com/ChoiceCoin/Voting/tree/main/AlphaVote/AlphaVote1), so we can integrate the previous functionality with @fionnachan's design.

**Comment by ChoiceCoin** [comment]
Also, @Arch222 is there an error readout? What troubleshooting have you tried?

**Pull request merged**
