### PR TITLE
choice coin

### PR DESCRIPTION
**Pull request by shewnstic1**
big project

### CODE REVIEW

**Comment by Mezstiles** [comment]
Wonderful project

**Comment by Sasxy** [comment]
What a great innovation.

**Comment by junyxp** [comment]
Big project with different..

**Comment by junyxp** [comment]
https://github.com/ChoiceCoin/Voting/pull/483#issuecomment-917883740


QEHWBH5JHNFNWEMLZULDO7LJ2Z2FLW4TKMLWGGUOKLCWJYDZ44HPSGTYBA

**Pull request closed without merging**
