### PR TITLE
feat: multiwallet option

### PR DESCRIPTION
**Pull request by ScMofeoluwa**
different wallet for different vote option

### CODE REVIEW

**Comment by Bhaney44** [comment]
When I run the file I get:` Enter ID of the vote of your choice`. But I am not sure what this is asking for or what to do next. Please elaborate.

**Comment by ScMofeoluwa** [comment]
> When I run the file I get:` Enter ID of the vote of your choice`. But I am not sure what this is asking for or what to do next. Please elaborate.

In a case of multiple vote options, the user gets to input the ID of the vote option of their choice and proceeds to vote for that option

**Comment by Bhaney44** [comment]
I am not familiar with the ID of the vote option. Could you please provide an example for what that would be? Thanks!

**Comment by ScMofeoluwa** [comment]
> I am not familiar with the ID of the vote option. Could you please provide an example for what that would be? Thanks!

Given a list of vote options:
1. Vote for candidate 1
2. Vote for candidate 2
3. Vote for candidate 3
Each vote option has an ID(in this case 1,2 and 3)
so by inputing the ID of your choice, you get to vote for that particular vote option

**Comment by ScMofeoluwa** [comment]
> > I am not familiar with the ID of the vote option. Could you please provide an example for what that would be? Thanks!
> 
> Given a list of vote options:
> 
> 1. Vote for candidate 1
> 2. Vote for candidate 2
> 3. Vote for candidate 3
>    Each vote option has an ID(in this case 1,2 and 3)
>    so by inputing the ID of your choice, you get to vote for that particular vote option



> > I am not familiar with the ID of the vote option. Could you please provide an example for what that would be? Thanks!
> 
> Given a list of vote options:
> 
> 1. Vote for candidate 1
> 2. Vote for candidate 2
> 3. Vote for candidate 3
>    Each vote option has an ID(in this case 1,2 and 3)
>    so by inputing the ID of your choice, you get to vote for that particular vote option

the address of the vote option then gets accessed from the `vote_addresses` dictionary and choice is sent to the address

> `vote_addresses

>

**Comment by ScMofeoluwa** [comment]
> > I am not familiar with the ID of the vote option. Could you please provide an example for what that would be? Thanks!
> 
> Given a list of vote options:
> 
> 1. Vote for candidate 1
> 2. Vote for candidate 2
> 3. Vote for candidate 3
>    Each vote option has an ID(in this case 1,2 and 3)
>    so by inputing the ID of your choice, you get to vote for that particular vote option

the address of the vote option then gets accessed from the `vote_addresses` dictionary and choice is sent to the address

**Comment by Bhaney44** [comment]
```
Enter ID of the vote of your choice2
Traceback (most recent call last):
  File "mwall.py", line 62, in <module>
    vote()
  File "mwall.py", line 56, in vote
    vote_address = vote_addresses[id_]
KeyError: '2'
```

**Pull request merged**
